### ISSUE TITLE
Makes asciify-image dependency conditional

### ISSUE THREAD

**Issue by carlostxm** [uber-web/probe.gl#34]
Hi,

This issue is related to https://github.com/uber/deck.gl/issues/2241. Please, try to make asciify-image conditional in order to avoid to bring the +90 dependencies into the project.

Thanks,

Carlos.

**Comment by ibgreen** [comment]
Published as 2.0.0-beta.1

**Comment by carlostxm** [comment]
@ibgreen That is agile :1st_place_medal:
