### ISSUE TITLE
Publish new version with LICENSE file

### ISSUE THREAD

**Issue by bclinkinbeard** [uber-web/probe.gl#76]
As of https://github.com/uber-web/ocular/pull/197, published modules properly include their full license text. deck.gl has [published](https://github.com/uber/deck.gl/issues/3151#issuecomment-497133270) v7.0.10 in response, can this repo do the same? Thanks!

**Comment by ibgreen** [comment]
LICENSE is now being published, compare:

- https://unpkg.com/probe.gl@3.1.0-alpha.2/LICENSE
- https://unpkg.com/probe.gl@3.1.0-alpha.1/LICENSE

@tsherif since you have probe.gl 1.1.0 on alpha I will leave it to you to publish the production version.  `npm run publish prod` when you are ready.

**Comment by bclinkinbeard** [comment]
Is it possible to publish 3.0.3 with LICENSE? probe.gl is a transitive dependency, so pre-release versions aren't used.

**Comment by bclinkinbeard** [comment]
Thanks!
