### ISSUE TITLE
Stats: types should be set on Stats, not StatsWidget

### ISSUE THREAD

**Issue by ibgreen** [uber-web/probe.gl#84]
As it stands, the app instantiating a `StatsWidget` needs to know the names and types of individual stats in the `stats` object. This contradicts the idea of a Stats object containing a "bag" of useful but non-documented stats, and adds a bunch of fragile "boilerplate" code to apps.

**Comment by tsherif** [comment]
I don't feel the stats object should contain information about how it will be displayed, but one compromise I was thinking about is that the object could contain a `typeHint` property that could indicate to other systems the type of the contained data (e.g. `memory`, `time`, `count`). The stats widget could have default formatters for these types, but the application would also be free to override them.

**Comment by ibgreen** [comment]
That would absolutely work. 

Though I must admit that my expectation is that 99% percent of applications will be happy with the defaults. (I.e. will the extra hour spent documenting and adding test cases for a new type hints mechanism be justified for a feature we might not use?).

A slightly simpler way would be to just add default formatters on the stats and let the StatsWidget optionally override them.
